name: Deploy frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      deployments: write
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: yarn.lock

      # - name: Setup Font Awesome
      #   run: |
      #     npm config set "@fortawesome:registry" https://npm.fontawesome.com/
      #     npm config set "//npm.fontawesome.com/:_authToken" ${{ secrets.FA_TOKEN }}

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn build-only

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
